### ISSUE TITLE
The workaround to get Verification Code doesn't work

### ISSUE THREAD

**Issue by OscarrrJ92** [CharlesGillanders/homeassistant-alphaESS#186]
Hi there,

I tried to follow your guide to connect to the AlphaCloud since I have an AlphaESS battery through this link: https://github.com/CharlesGillanders/homeassistant-alphaESS. I tried the workaround for getting a Verification Code, but I noticed in the https://www.postman.com/poshy163/alphaess/request/uns7ntg/getverificationcode?tab=scripts code that this is not the getverificationcode script, but looks like a copy of the Discharge script. 

Can you check this for me please and correct it if neccessary, so I could get with the correct script a verification code. This would help me a lot! :)

Hope you can set it right. Thanks in advance!

Best regards,

Oscar

**Comment by CharlesGillanders** [comment]
@Poshy163 This looks to be something broken in your existing postman collection.  Would you be able to take a look?

**Comment by Poshy163** [comment]
Heya @OscarrrJ92. should be fixed now, give it a go

**Comment by OscarrrJ92** [comment]
Heya @Poshy163,

Thanks for the fast response! Unfortunately I still get "200" as a return. I guess something in the "Scripts" of /getVerificationCode still doesn't go well. I added a printscreen of the forked collection. Can you please check this?

Thank you very much!

![Image](https://github.com/user-attachments/assets/71076709-113c-4191-8314-211243ead297)

**Comment by Poshy163** [comment]
Ah apologies, updated that now

**Comment by Poshy163** [comment]
Strange, as it seems to be working here with no issues, maybe its worth going to alphaess support to ask? 

![Image](https://github.com/user-attachments/assets/f16a8ab3-c79f-4261-84a7-d66659ca1b7b)

![Image](https://github.com/user-attachments/assets/324889bf-5f8a-4a74-9a8b-2d4bf1600e5d)

**Comment by OscarrrJ92** [comment]
Hi @Poshy163 

I followed the exact steps, forked the collection, filled the variables, but unfortunately still get this message:

![Image](https://github.com/user-attachments/assets/119bdf7d-6b8c-47dc-ba4e-1491427b982d)

I'll contact AlphaESS. Thank you very much for your time and patience! :)
