### ISSUE TITLE
cloud.alphaess breaks add on?

### ISSUE THREAD

**Issue by Spookster** [CharlesGillanders/homeassistant-alphaESS#20]
It seems the recent domain change (1/7) from www.alphaess.com to cloud.alphaess.com has broken the integration?

**Comment by corvidus** [comment]
The issue's been raised in the Dev's API repo as well: 
https://github.com/CharlesGillanders/alphaess/issues/2

Hopefully they're able to update.

**Comment by rafkra** [comment]
Is there a way to fix this locally? I can't find the files from the https://github.com/CharlesGillanders/alphaess/ library on my box.

**Comment by CharlesGillanders** [comment]
I have merged the change that was requested in the API repo to update the hostname.  The new version of the pypi package with that change included is 0.0.4 - if you want to make a quick fix locally you can update manifest.json to specify "requirements": ["alphaess==0.0.4"] or just pull down the latest version of this project from github.  You will need to restart your home assistant and it will automatically install the updated version of the API package.

**Comment by CharlesGillanders** [comment]
Re-opened so that it's listed at the top of the issues list for the next few days,

**Comment by qbushome** [comment]
Thanks for this quick modification. Since my problem was not resolved, I signed out from the integration. Uninstalled and reinstalled it. Now I het an authentication error. I double checked my credentials. Any idea what van be wrong?

**Comment by CharlesGillanders** [comment]
> Thanks for this quick modification. Since my problem was not resolved, I signed out from the integration. Uninstalled and reinstalled it. Now I get an authentication error. I double checked my credentials. Any idea what van be wrong?

Do you have any error message either in the UI or in the log files?

**Comment by qbushome** [comment]
Sorry for the late reply (on holiday with limited computer access).
Where can I find logfiles ?
In the UI I go to "+ integrations", select the integration, fill in the username+password.

I get
![Schermafbeelding 2022-07-09 om 17 18 08](https://user-images.githubusercontent.com/72740143/178111859-860169e7-5c17-409b-ad92-bf9c919129ab.JPG)

Since the integration is not installed I don't know where else to look for logs.

**Comment by CharlesGillanders** [comment]
Any error message showing up in home assistant in Settings/System/Logs?

Example here’s my logs from earlier today when Iost internet connectivity and the alpha ESS integration wasn’t able to collect metrics.

![A92B40A5-E125-413C-B5F0-38A31F3372AD](https://user-images.githubusercontent.com/53312816/178112913-4fc59b94-4cb3-491a-94c1-ba5e6a4fbfc3.jpeg)

**Comment by qbushome** [comment]
Nothing to see in this log. Only unrelated errors for other integrations.
I suspect this is because the integration is not active.

**Comment by gref1966** [comment]
I had also the same problem as above, after removing all alphaess-files from /config/custom_components/alphaess I could not be able to install the intagration. 
![image](https://user-images.githubusercontent.com/79963099/179469306-0c1d7f4d-24f9-4b0c-b8e7-85a46331b5cd.png)
Retyping the credentials does not help to install the integration.

**Comment by CharlesGillanders** [comment]
> I had also the same problem as described above, after removing all alphaess-files from /config/custom_components/alphaess I could not be able to install the intagration. ![image](https://user-images.githubusercontent.com/79963099/179469306-0c1d7f4d-24f9-4b0c-b8e7-85a46331b5cd.png) Retyping the credentials does not help to install the integration.
> 
> Then I uploades all files again and restarted HomeAssistant ... and now it works again

@gregpetersau identified what I believe is the problem, please try enabling advanced mode.

https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/25

Enable Advanced Mode using Profile (click on your username at the bottom of the navigation column) -> Advanced Mode -> On

**Comment by CharlesGillanders** [comment]
> Sorry for the late reply (on holiday with limited computer access). Where can I find logfiles ? In the UI I go to "+ integrations", select the integration, fill in the username+password.
> 
> I get ![Schermafbeelding 2022-07-09 om 17 18 08](https://user-images.githubusercontent.com/72740143/178111859-860169e7-5c17-409b-ad92-bf9c919129ab.JPG)
> 
> Since the integration is not installed I don't know where else to look for logs. I'm running 2022.6.6 with Alpha ESS to MQTT (0.1.4).
> 
> I doublechecked the credentials on https://cloud.alphaess.com/

@gregpetersau identified what I believe is the problem, please try enabling advanced mode.

See Issue https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/25

Enable Advanced Mode using Profile (click on your username at the bottom of the navigation column) -> Advanced Mode -> On
